"""Added ClientTask model

Revision ID: 3c1b7a1eb4cf
Revises: d69223d0cf2d
Create Date: 2023-12-12 14:18:11.795528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1b7a1eb4cf'
down_revision: Union[str, None] = 'd69223d0cf2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_tasks',
    sa.Column('client_task_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cleaning_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('client_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_tasks')
    # ### end Alembic commands ###
