"""Added CleaningTask model

Revision ID: d69223d0cf2d
Revises: c8cc96fe019a
Create Date: 2023-12-12 13:22:35.543080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69223d0cf2d'
down_revision: Union[str, None] = 'c8cc96fe019a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('cleaner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cleaner_id'], ['cleaners.cleaner_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleaning_tasks')
    # ### end Alembic commands ###
